### ISSUE TITLE
README doesn't contain all the steps necessary to run

### ISSUE THREAD

**Issue by mikedotexe** [nearprotocol/corgis#3]
A user needs to know to use `near deploy` at some point in the process of following the steps to the README.

Steps to reproduce: follow the readme as it currently is, with a fresh clone of the repository.

**Comment by icerove** [comment]
I will add more instructions

**Comment by AnaisUrlichs** [comment]
I followed the steps in the current README both on Ubuntu and then on Windows.

It worked like expected on Ubuntu.

However, on Windows (both npm and yarn installed)
`npm install && npm run start`
does not run since it does not recognize `&&` (?)
![npmdifferencewindows](https://user-images.githubusercontent.com/33576047/85224814-31006b00-b3cd-11ea-95d4-07991b28abea.PNG)

Also, running both commands one after the other throws the following error
![builderror](https://user-images.githubusercontent.com/33576047/85224772-ea127580-b3cc-11ea-80f6-c41c2cccab81.PNG)

However, running
`yarn install`
and then
`yarn start`

works as expected

**Comment by mikedotexe** [comment]
Good observation, @AnaisUrlichs !

**Comment by icerove** [comment]
I updated the ReadMe steps
